paths:
  cleaned_dir: /data2/david.ellis/public/HCPA/myderivatives/cleaned
  csmooth_dir: /data2/david.ellis/public/HCPA/myderivatives/csmooth_nr
  gaussian_dir: /data2/david.ellis/public/HCPA/myderivatives/gaussian
  output_root: /data2/david.ellis/public/HCPA/myderivatives/fpr
  mask_path: null
  subjects_glob: sub-*

smoothing:
  fwhm_values: [3, 6, 9, 12]

feat:
  fsf_template: /data2/david.ellis/public/HCPA/code/fpr/template.fsf
  container: /data2/david.ellis/public/HCPA/code/tractography/fslantsnipype.sif
  log_dir: /data2/david.ellis/public/HCPA/cache/fpr/logs
